### ISSUE TITLE
Proposal peer review by MildCats

### ISSUE THREAD

**Issue by visren** [INFO-526-F24/project-01-StockSleuths#2]
The following is the peer review of the project proposal by MildCats. The team members that participated in this review are
- Siva Bhargav Ravula -  @Siva-Bhargav
- Solman Sarva - @sarvasolomonraju
- Vishnu Rendla - @visren
- Prajwal Sathyanarayana - @PRAJWAL2108
- Sankalp Sethi - @sethisankalp
- Tirth Shah- @tirthshah1-DA
- Yash Salokhe - @Yash-Salokhe

**- Describe the goal of the project.**
StockSleuths are trying to explore the major global conflict (Russia-Ukraine War) and its impact on the US economy, as measured by various sentiment and investment indicators. 

**- Describe the data used or collected.**
Team used 3 different datasets that are relevant to the topic they are trying to discuss, datasets are from credible and official  sources which have been mentioned under Citations. They are aware of potential missing data and are aware of the preprocessing step that needs to be taken.

**- Describe how the research question will be answered, e.g. what approaches / methods will be used.**
Before proceeding with the analysis, they will clean and preprocess the data to address any missing or inconsistent values, ensuring the datasets are ready for analysis. They will also conduct exploratory data analysis (EDA) to identify initial patterns and trends in the data. For the first question they will visualize trends using a time series plot and explore the relationship between stock trends and oil prices through a scatter plot. For the second, they will investigate how consumer sentiment has changed in along with the US Stock Market Performance Measure and oil prices and will be visualized using a box plot for distribution of consumer sentiment and a line plot to depict trends over time.

**- Is there anything that is unclear from the proposal?**
How the team is going to merge/clean the data was slightly unclear and what specific statistical methods would the team be using for the analysis could have been mentioned.

**- Provide constructive feedback on how the team might be able to improve their project.**
To emphasize more on how global conflicts impact our economies, team can also maybe show a line graph showing spikes/dips (if any) in the economy and identify times where wars might have occurred.

**- What aspect of this project are you most interested in and would like to see highlighted in the presentation.**
We are most interested in seeing the final results of your analysis. We'd like to see exactly how U.S. crude oil prices, US Stock Market Performance Measure, consumer sentiment, and inflation expectations have reacted to and changed due to the conflict. We are aware many of these metrics have experienced dramatic changes, so we hope you can present that in an intriguing way. 

**- Provide constructive feedback on any issues with file and/or code organization.**
There isn't much raw code yet, but the present code follows convention and is correctly formatted. File structure and organization are also standard and easy to follow. We recommend you to continue these good practices, especially during the analysis stage when more code will be entered. 

**- (Optional) Any further comments or feedback?**
Team can use a primary key from all the datasets, specifically the time column to make sure the dates align.

**Comment by remisublette** [comment]
Thank you!
