### ISSUE TITLE
Proposal peer review by ViZzards

### ISSUE THREAD

**Issue by VikRuhil1990** [INFO-526-F24/project-01-StockSleuths#3]
The following is the peer review of the project proposal by ViZZards. The team members that participated in this review are 

- Vik Ruhil - @vikruhil1990
- Yash Sharma - @Ash-Y-28
- Smit Shah - @smitshah02
- Raghav Upadhyay - @raghav-upadhyay2002
- Chaitanya Suralkar - @ChaitanyaS99
- Tushar Shrivastava - @Tushar-Shrivastava
- Partha Vemuri - @Partha-Vemuri

- Describe the goal of the project.
This project examines the impact of the Russia-Ukraine conflict on the U.S. economy, with a particular focus on key indicators such as oil prices and stock market trends. By analyzing data from before the conflict, its outbreak in February 2022, and continuing through to the present, the goal is to identify how economic dynamics have evolved. The analysis highlights the influence of the U.S.'s role as a major ally of Ukraine, providing a deeper understanding of how global disruptions affect domestic markets.

- Describe the data used or collected.
There are 3 dataset used in this project-
1. Dataset 1: US Stock Market Data from Kaggle, sp500_stocks.csv  (<https://www.kaggle.com/datasets/andrewmvd/sp-500-stocks>)
2. Dataset 2: EIA data pswrgvwall.xls 
(<https://www.eia.gov/petroleum/gasdiesel/>)
3. Dataset 3: Consumer Sentiment & Inflation data from FRED umcsent.csv and MICH.csv -merged together- (<https://fred.stlouisfed.org/series/UMCSENT> <https://fred.stlouisfed.org/series/MICH>)

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
Question 1: How have US Stock Market trends and oil prices changed since the beginning of the Russia/Ukraine Conflict?
The S&P 500 dataset comprises the share values of the 500 largest publicly traded companies in the United States, collectively representing approximately 75% of the total market capitalization of the U.S. stock market. By analyzing the fluctuations in the values of these companies' stocks, the dataset provides valuable insight into the broader health of the U.S. economy. Comparing the changes in the index before and during the Russia-Ukraine conflict allows us to assess the economic impact of the war, highlighting how global events have influenced investor sentiment, stock market performance, and overall economic conditions in the U.S.

Question 2: How has consumer sentiment, stock trends, oil prices, and inflation expectations changed over time during the Russia/Ukraine conflict?
Analyzing consumer sentiment, oil prices, and inflation trends over the years will offer a clearer picture of the economic impact during the Russia-Ukraine conflict compared to the period before the war. Consumer sentiment reflects the confidence of U.S. households in the economy, which can influence spending and investment behavior. Oil prices, as a critical driver of global energy costs, play a significant role in shaping inflationary pressures and the broader cost of living. Tracking these factors over time helps to understand how the conflict has affected both consumer behavior and broader economic conditions. By comparing these metrics from before and during the war, we can gain deeper insights into how the conflict has disrupted the economy, affecting everything from household purchasing power to inflationary trends and the overall stability of the U.S. economy.

- Is there anything that is unclear from the proposal?
According to our team following things we believe is unclear-

1. There are missing values in Dataset 3, and the variables in the merged dataset do not align with the necessary variables to answer the research questions.

2. Dataset 2 contains multiple datasets combined into a single Excel file, making it unclear which sub-dataset should be used to address specific questions. Additionally, it is unclear how to analyze the global oil price impact resulting from the war.

3. The dataset lacks clarity on the parameters used to assess consumer sentiment, and the explanation provided does not specify the metrics or methods applied.

4. The CSI index cannot be included in the inflation calculation. The inflation data in the dataset does not align with consumer sentiment data, such as MICH and UMSCENT. Without a proper correlation between these variables, it is not possible to accurately determine the impact on the economy.

- Provide constructive feedback on how the team might be able to improve their project.

Handle Missing Values in Dataset 3:

Action: Review the dataset for missing values and decide on an appropriate strategy for imputation, whether by using mean, median, or forward/backward filling, depending on the context. Alternatively, if imputation isn't suitable, consider removing rows with missing values, but ensure this doesn't significantly impact the analysis. Making sure the necessary overlap is not missing.
Improvement: This will ensure that the dataset is complete and usable for answering the research questions, providing a more reliable foundation for analysis.

Clarify Sub-Datasets in Dataset 2:

Action: Select from Dataset 2 a clearly defined sub-datasets with accompanying documentation, detailing what each dataset represents and which specific data points will be used for each research question.
Improvement: This will ensure that the analysis is focused and structured, making it clear which variables are being used to answer each question. Specifically, for the global oil price impact, isolate the oil price data and correlate it with relevant geopolitical events, such as the Russia-Ukraine conflict.

Clarify Consumer Sentiment Parameters:

Action: Clearly define the parameters used to assess consumer sentiment in the dataset. If the dataset uses specific indices (such as the University of Michigan Consumer Sentiment Index), explain how these indices are measured and their relevance to the analysis.
Improvement: This will help establish a clear and transparent methodology for how consumer sentiment is being quantified, enhancing the credibility of the analysis.

Ensure Consistency Between Inflation and Consumer Sentiment Data:

Action: Align the inflation data with consumer sentiment variables, such as MICH and UMSCENT, to ensure that the analysis reflects how inflation impacts consumer sentiment and vice versa. The CSI index should be excluded from inflation calculations if it does not correlate with inflationary trends.
Improvement: This will ensure that the economic models being developed are consistent and that variables being analyzed have a logical relationship, allowing for more accurate conclusions about the impact of the Russia-Ukraine conflict on U.S. economic conditions.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

The most intriguing aspect of this project is how the global geopolitical event, specifically the Russia-Ukraine conflict, has impacted key economic indicators such as oil prices, consumer sentiment, and inflation. These elements provide a holistic view of how global disruptions can ripple through domestic economies, influencing everything from individual consumer behavior to the performance of large-scale financial markets like the S&P 500. In particular, I would like to see the correlation between oil price fluctuations and stock market trends during the conflict period, as well as a clear analysis of how consumer sentiment (captured by the MICH and UMSCENT data) has evolved alongside inflationary pressures. Highlighting the economic shifts before and during the war will offer valuable insights into the broader economic impact and potentially serve as a case study for future geopolitical conflicts.

- Provide constructive feedback on any issues with file and/or code organization.

File Organization:

Issue: The datasets in the current Excel file in dataset 2 are combined, making it unclear which sub-dataset should be used for specific questions. This could lead to confusion and inefficiencies when analyzing the data. Select variables based on all datasets what can answer your question.
Feedback: Organize the datasets into separate files or create a clear index within the current Excel file to categorize the different datasets. Each dataset should be well-documented, indicating its specific purpose and how it connects to the project’s analysis. For example, separating oil price data, consumer sentiment data, and inflation data into distinct sheets or files will make it easier to pinpoint which dataset is needed for each aspect of the analysis.

Code Organization:

Issue: The code may be handling multiple tasks without clear separation between different analyses (e.g., oil price analysis, consumer sentiment analysis, and inflation calculation).
Feedback: Break down the code into modular functions or scripts, each dedicated to a specific analysis. For example, create separate code chunks for cleaning and preprocessing the data, another for analyzing oil price impacts, and yet another for evaluating consumer sentiment trends. This approach will improve readability, maintainability, and ease of troubleshooting. Additionally, ensure that variable names and function names are descriptive and consistent, which will further enhance the clarity of the code.

- (Optional) Any further comments or feedback?

**Comment by remisublette** [comment]
Thank you!
