### ISSUE TITLE
Write-up feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO-526-F24/project-01-StockSleuths#6]
Dear @INFO-526-F24/stocksleuths : Below is the score breakdown for your write-up. Details of things that should be updated/revised are provided in separate issues. As you address them, you should close the individual issues.

You can do this in one of two ways:

- On GitHub, by clicking on Close issue
- Via a commit that directly addresses the issue.

Please use the second method wherever a fix can be tied to a commit. If you preface your commit messages with "Fixes", "Fixed", "Fix", "Closed", or "Close", the issue will be closed when you push the changes to your repo. For example, suppose you want to close issue `#2` which, hypothetically, suggested that you add a new line to the README, your commit message can say something like `Add a new line to the README, closes #2`.

Once you've closed all of the other issues, close this one as well, so that going into the presentation you have no open issues remaining.

## Write-up

Category | Available | Earned | Feedback
-- | -- | -- | --
Introduction/Data | 6 | 5 | The introduction has a clear and concise overview of the project goals and data used. However, the description of the dataset could be expanded to include more details on its source, preprocessing, or any assumptions made during collection.
Methodology | 10 | 9 | The methodology is sound and aligns with the project objectives. However, it lacks depth in justifying why specific techniques were chosen over others (such as standardization). Including comparisons to alternative approaches.
Results | 14 | 13 | The results are well-presented, and visualizations are informative. However, a few visualizations could use better labeling and annotations to improve clarity. 
Discussion | 6 | 5 | The discussion is thoughtful and provides valuable insights connecting the results to the research questions. However, it could benefit from a more critical evaluation of the limitations and potential biases in the analysis. Suggesting future research directions would also enhance this section.
Organization + Formatting | 4 | 4 | The report is well-organized and formatted, making it easy to follow. The structure is logical, and the visual presentation is clean. However, minor tweaks to headings or spacing could further improve readability.
Total | 40 | 36 | The report is strong overall, but there is room for improvement in the depth of the methodology, clarity of visualizations, and critical analysis in the discussion section.

<hr>
<h3><strong>General Feedback</strong></h3>
<ul>
<li>The report demonstrates good technical execution but would benefit from a stronger focus on justifying the chosen methodologies and critically evaluating the results.</li>
<li>Adding more detail to the dataset description and highlighting assumptions would enhance transparency and reproducibility.</li>
<li>Visualizations could be improved with better annotations and labels to ensure that they are intuitive and directly support the discussion.</li>
<li>Including a limitations section and suggestions for future research would elevate the discussion section and reflect deeper critical thinking.</li>
</ul></body></html>

**Comment by remisublette** [comment]
Thank you for the feedback Prof.!
